USE BRAINSTORMAPP

CREATE TABLE REUNIONES (
    ID_REUNION INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255),
    DESCRIPCION TEXT,
    FECHA_HORA_INICIO TIMESTAMP,
    FECHA_HORA_FIN TIMESTAMP,
    ID_CREADOR INT,
    FECHA_CREACION TIMESTAMP,
    FOREIGN KEY (ID_CREADOR) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE PARTICIPANTES (
    ID_PARTICIPANTE INT AUTO_INCREMENT PRIMARY KEY,
    ID_REUNION INT,
    ID_USUARIO INT,
    ROL VARCHAR(50),
    FOREIGN KEY (ID_REUNION) REFERENCES REUNIONES(ID_REUNION),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE ACTAS (
    ID_ACTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_REUNION INT,
    CONTENIDO TEXT,
    FECHA_CREACION TIMESTAMP,
    FOREIGN KEY (ID_REUNION) REFERENCES REUNIONES(ID_REUNION)
);

CREATE TABLE NOTIFICACIONES (
    ID_NOTIFICACION INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    MENSAJE TEXT,
    FECHA_ENVIO TIMESTAMP,
    LEIDA BOOLEAN,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE TAREAS (
    ID_TAREA INT AUTO_INCREMENT PRIMARY KEY,
    ID_REUNION INT,
    ID_ASIGNADO INT,
    DESCRIPCION TEXT,
    FECHA_LIMITE TIMESTAMP,
    COMPLETADA BOOLEAN,
    FOREIGN KEY (ID_REUNION) REFERENCES REUNIONES(ID_REUNION),
    FOREIGN KEY (ID_ASIGNADO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE MENSAJES_CHAT (
    ID_MENSAJE INT AUTO_INCREMENT PRIMARY KEY,
    ID_REUNION INT,
    ID_USUARIO INT,
    CONTENIDO TEXT,
    FECHA_ENVIO TIMESTAMP,
    FOREIGN KEY (ID_REUNION) REFERENCES REUNIONES(ID_REUNION),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE SENTIMIENTOS (
    ID_SENTIMIENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_REUNION INT,
    ID_USUARIO INT,
    SENTIMIENTO VARCHAR(50),
    PUNTUACION FLOAT,
    FECHA_HORA TIMESTAMP,
    FOREIGN KEY (ID_REUNION) REFERENCES REUNIONES(ID_REUNION),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE CONFIGURACION_APLICACION (
    ID_CONFIGURACION INT AUTO_INCREMENT PRIMARY KEY,
    CLAVE VARCHAR(255),
    VALOR VARCHAR(255),
    DESCRIPCION TEXT
);

CREATE TABLE ROLES (
    ID_ROL INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    DESCRIPCION TEXT
);

CREATE TABLE PERMISOS (
    ID_PERMISO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    DESCRIPCION TEXT
);

CREATE TABLE ROL_PERMISO (
    ID_ROL_PERMISO INT AUTO_INCREMENT PRIMARY KEY,
    ID_ROL INT,
    ID_PERMISO INT,
    FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL),
    FOREIGN KEY (ID_PERMISO) REFERENCES PERMISOS(ID_PERMISO)
);

CREATE TABLE LOGS_ACTIVIDAD (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    ACCION VARCHAR(255),
    FECHA_HORA TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE FEEDBACK_USUARIOS (
    ID_FEEDBACK INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    COMENTARIO TEXT,
    PUNTUACION INT,
    FECHA_CREACION TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);
