USE BRAINSTORM_BD;

-- Eliminar tablas en el orden correcto para respetar las claves foráneas
DROP TABLE IF EXISTS FEEDBACK_USUARIOS;
DROP TABLE IF EXISTS LOGS_ACTIVIDAD;
DROP TABLE IF EXISTS ROL_PERMISO;
DROP TABLE IF EXISTS PERMISOS;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS CONFIGURACION_APLICACION;
DROP TABLE IF EXISTS SENTIMIENTOS;
DROP TABLE IF EXISTS MENSAJES_CHAT;
DROP TABLE IF EXISTS TAREAS;
DROP TABLE IF EXISTS NOTIFICACIONES;
DROP TABLE IF EXISTS ACTAS;
DROP TABLE IF EXISTS PARTICIPANTES;
DROP TABLE IF EXISTS REUNIONES;
DROP TABLE IF EXISTS USUARIOS;
